# loc | motor  |   min     |   max
#     |        |deg  pwm   | deg   pwm
#-------------------------------------
#     |  11    | 0  = 240  | 210 = 610 
# bl  |  10    | 0  = 525  | 180 = 180  
#     |  9     | 35 = 490  | 155 = 210 
#-------------------------------------
#     |  8     | 0  = 240  | 210 = 620 
# fl  |  7     | 0  = 520  | 180 = 180 
#     |  6     | 37 = 220  | 150 = 510 
#-------------------------------------
#     |  5     | 0  = 610  | 210 = 210 
# fr  |  4     | 0  = 180  | 180 = 530 
#     |  3     | 33 = 490  | 155 = 210 
#-------------------------------------
#     |  2     | 0  = 620  | 210 = 240 
# br  |  1     | 0  = 180  | 180 = 520 
#     |  0     | 35 = 200  | 155 = 480 
#-------------------------------------

#    home - [t1,t2,t3]
#    home_pos: [x,y,z]

br:
    motors: [0,1,2]
    home: [90.0, 40.0, 100.0]
    home_pos: [40.0,60.0,175.0]

    min_pwm: [140,180,610]
    max_pwm: [460,520,340]
    min_angle: [15 ,0  ,40 ]
    max_angle: [162,180,180]

fr:
    motors: [3,4,5]
    home: [90.0, 40.0, 100.0]
    home_pos: [40.0,60.0,175.0]

    min_pwm: [490,180,600]
    max_pwm: [210,530,330]
    min_angle: [15 ,0  ,40]
    max_angle: [162,180,180]

fl:
    motors: [6,7,8 ]
    home: [90.0, 40.0, 100.0]
    home_pos: [40.0,60.0,175.0]

    min_pwm: [220,510,250]
    max_pwm: [510,180,520]
    min_angle: [15 ,0  ,40]
    max_angle: [170,180,180]


bl:
    motors: [ 9,10,11]
    home: [90.0, 40.0, 100.0]
    home_pos: [40.0,60.0,175.0]



    min_pwm: [490,515,250]
    max_pwm: [210,180,520]

    min_angle: [15 ,0  ,40]
    max_angle: [162,180,180]





