legs_name: [bl,fl,fr,br]

legs_transform:
            #pose: x y z         ori: x y z w
  bl:    [0, 0, 0,                   0,0,0,1]  
  fl:    [0, 0, 0,                   0,0,0,1]  
  fr:    [0,0,0,                     0,0,0,1]  
  br:    [0,0,0,                     0,0,0,1]  


start_pos:
  #pose:    x   y    z         
  bl:    [0, 60, 125]  
  fl:    [0, 60, 125]  
  fr:    [0, 60, 125]  
  br:    [0, 60, 125]  
  

start_speed: 10

forward_x_walk: 50
forward_z_walk: 40
forward_y_walk: 0

turn_x_walk: 35
turn_z_walk: 30
turn_y_walk: 15


