legs_name: [bl,fl,fr,br]

legs_transform:
            #pose: x y z         ori: x y z w
  bl:    [0, 0, 0,                   0,0,0,1]  
  fl:    [0, 0, 0,                   0,0,0,1]  
  fr:    [0,0,0,                     0,0,0,1]  
  br:    [0,0,0,                     0,0,0,1]  


start_pos:
  #pose:    x   y    z         
  bl:    [-20, 60, 130]  
  fl:    [-20, 60, 130]  
  fr:    [-20, 60, 130]  
  br:    [-20, 60, 130]  

start_speed: 5

forward_x_walk: 35
forward_z_walk: 35
forward_y_walk: 20

turn_x_walk: 25
turn_z_walk: 25

