legs_name: [bl,fl,fr,br]

legs_transform:
            #pose: x y z         ori: x y z w
  bl:    [0, 0, 0,                   0,0,0,1]  
  fl:    [0, 0, 0,                   0,0,0,1]  
  fr:    [0,0,0,                     0,0,0,1]  
  br:    [0,0,0,                     0,0,0,1]  


start_pos:
  #pose:    x   y    z         
  bl:    [-15, 60, 120]  
  fl:    [-15, 60, 120]  
  fr:    [-15, 60, 120]  
  br:    [-15, 60, 120]  

start_speed: 7

forward_x_walk: 45
forward_z_walk: 35
forward_y_walk: 15

turn_x_walk: 35
turn_z_walk: 30
turn_y_walk: 15


