# loc | motor  |   min     |   max
#     |        |deg  pwm   | deg   pwm
#-------------------------------------
#     |  11    | 0  = 240  | 210 = 610 
# bl  |  10    | 0  = 525  | 180 = 180  
#     |  9     | 35 = 490  | 155 = 210 
#-------------------------------------
#     |  8     | 0  = 240  | 210 = 620 
# fl  |  7     | 0  = 520  | 180 = 180 
#     |  6     | 37 = 220  | 150 = 510 
#-------------------------------------
#     |  5     | 0  = 610  | 210 = 210 
# fr  |  4     | 0  = 180  | 180 = 530 
#     |  3     | 33 = 490  | 155 = 210 
#-------------------------------------
#     |  2     | 0  = 620  | 210 = 240 
# br  |  1     | 0  = 180  | 180 = 520 
#     |  0     | 35 = 200  | 155 = 480 
#-------------------------------------


map_angel_pwm:
    min_pwm_val: [200,180,620,490,180,610,220,520,210,490,525,240]
    max_pwm_val: [480,520,240,210,530,210,510,180,450,210,180,610]
    min_angle_val : [15 ,0  ,0  ,15 ,0  ,0  ,15 ,0  ,0  ,15 ,0  ,0]
    max_angle_val : [162,180,210,162,180,210,170,180,210,162,180,210]

name_id_maping:
    bl: [9,10,11]
    fl: [6,7,8]
    fr: [3,4,5]
    br: [0,1,2]

home:
    pos: [90.0, 45.0, 60.0] 


